version: 0.1
prod:
  global:
    parameters:
      stack_name: youtube-comment-sentiment-analysis
  build:
    parameters:
      use_container: true
  deploy:
    parameters:
      template_file: template.yaml
      fail_on_empty_changeset: false
      resolve_s3: true
      capabilities:
        - CAPABILITY_IAM