version: 0.1

test:
  global:
    parameters:
      stack_name: test-youtube-comment-sentiment-analysis
      s3_bucket: test-sam-cli-artifacts-youtube-comment-sentiment-analysis
  local_invoke:
    parameters:
      template_file: .aws-sam/build/template.yaml
      event: events/event.json
  build:
    parameters:
      use_container: true
  package:
    parameters:
      template_file: .aws-sam/build/template.yaml
      output_template_file: packaged-testing-template.yaml
  deploy:
    parameters:
      template_file: packaged-testing-template.yaml
      disable_rollback: true
      parameter_overrides: "Env=test"
      fail_on_empty_changeset: false
      capabilities:
        - CAPABILITY_IAM

prod:
  global:
    parameters:
      stack_name: prod-youtube-comment-sentiment-analysis
      s3_bucket: prod-sam-cli-artifacts-youtube-comment-sentiment-analysis
  build:
    parameters:
      use_container: true
  package:
    parameters:
      template_file: .aws-sam/build/template.yaml
      output_template_file: packaged-prod-template.yaml
  deploy:
    parameters:
      template_file: packaged-prod-template.yaml
      disable_rollback: true
      parameter_overrides: "Env=prod"
      fail_on_empty_changeset: false
      capabilities:
        - CAPABILITY_IAM