version: 0.1
prod:
  global:
    parameters:
      stack_name: youtube-comment-sentiment-analysis
  build:
    parameters:
      use_container: true
  deploy:
    parameters:
      template_file: template.yaml
      fail_on_empty_changeset: false
      s3_bucket: aws-sam-cli-youtube-comment-sentiment-analysis
      capabilities:
        - CAPABILITY_IAM