AWSTemplateFormatVersion: '2010-09-09'

Transform: 
  - AWS::Serverless-2016-10-31

Description: Youtube comment sentiment analysis service

Parameters:
  Env:
    Type: String
    Default: test
    AllowedValues:
      - test
      - prod
    Description: Environment to deploy the stack

Resources:
  YoutubeCommentSentimentAnalysisFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${Env}-youtube-comment-sentiment-analysis
      Handler: app.lambda_handler
      CodeUri: ./src
      Description: Fetches comments from youtube video and performs sentiment analysis
      Architectures:
        - x86_64
      Runtime: python3.12
      Timeout: 30
      Tracing: Active
      Environment:
        Variables:
          POWERTOOLS_SERVICE_NAME: ProdYoutubeCommentSentimentAnalysis
          POWERTOOLS_METRICS_NAMESPACE: ProdYoutubeCommentSentimentAnalysis
          LOG_LEVEL: INFO
          BUCKET_NAME: !Ref S3Bucket
          ENVIROMENT: !Ref Env
      Policies: 
        - ComprehendBasicAccessPolicy: {}
        - S3WritePolicy:
            BucketName: !Ref S3Bucket
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn: !Sub arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:test/YoutubeSentimentAnalysis-CVq1ik
      Tags:
        Service: !Ref AWS::StackName
        Env: !Ref Env
      Events:
        DynamoDBStreamTrigger:
          Type: DynamoDB
          Properties:
            Stream: !GetAtt DynamoDBTable.StreamArn
            BatchSize: 100
            StartingPosition: LATEST

  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${Env}-youtube-comment-sentiment-analysis
      Tags:
        - Key: Service
          Value: !Ref AWS::StackName
        - Key: Env
          Value: !Ref Env

  GlueDatabase:
    Type: AWS::Glue::Database
    Properties:
      CatalogId: !Ref "AWS::AccountId"
      DatabaseInput:
        Name: !Sub ${Env}_youtube_comment

  GlueTable:
    Type: AWS::Glue::Table
    Properties:
      CatalogId: !Ref "AWS::AccountId"
      DatabaseName: !Ref GlueDatabase
      TableInput:
        Name: !Sub ${Env}_youtube_comment_analytics
        TableType: EXTERNAL_TABLE
        StorageDescriptor:
          Columns:
            - Name: id
              Type: string
            - Name: channel_id
              Type: string
            - Name: video_id
              Type: string
            - Name: text_display
              Type: string
            - Name: text_original
              Type: string
            - Name: author_display_name
              Type: string
            - Name: author_profile_image_url
              Type: string
            - Name: author_channel_url
              Type: string
            - Name: author_channel_id
              Type: string
            - Name: can_rate
              Type: boolean
            - Name: viewer_rating
              Type: string
            - Name: like_count
              Type: int
            - Name: published_at
              Type: timestamp
            - Name: updated_at
              Type: timestamp
            - Name: parent_id
              Type: string
            - Name: fetched_at
              Type: timestamp
            - Name: sentiment
              Type: string
            - Name: sentiment_score_positive
              Type: float
            - Name: sentiment_score_negative
              Type: float
            - Name: sentiment_score_neutral
              Type: float
          Location: !Sub s3://${S3Bucket}/data/
          InputFormat: "org.apache.hadoop.mapred.TextInputFormat"
          OutputFormat: "org.apache.hadoop.hive.ql.io.HiveIgnoreKeyTextOutputFormat"
          Compressed: false
          SerdeInfo:
            SerializationLibrary: org.openx.data.jsonserde.JsonSerDe
        Parameters:
          classification: json
          has_encrypted_data: "false"

  DynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ${Env}_youtube_comment_requests
      AttributeDefinitions:
        - AttributeName: video_id
          AttributeType: S
      KeySchema:
        - AttributeName: video_id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      StreamSpecification:
        StreamViewType: KEYS_ONLY
      TimeToLiveSpecification:
        Enabled: true
        AttributeName: ExpiryDate
      Tags:
        - Key: Service
          Value: !Ref AWS::StackName
        - Key: Env
          Value: !Ref Env

  AppRegistry:
    Type: AWS::ServiceCatalogAppRegistry::Application
    Properties:
      Name: !Sub ${Env}-youtube-comment-sentiment-analysis
      Description: Logical application grouping for Youtube Comment Sentiment Analysis resources
      Tags:
        service: !Ref AWS::StackName
        env: !Ref Env

  AppRegistryAssociation:
    Type: AWS::ServiceCatalogAppRegistry::ResourceAssociation
    Properties:
      Application: !Ref AppRegistry
      Resource: !Ref AWS::StackId
      ResourceType: CFN_STACK
  

Outputs:
  YoutubeCommentSentimentAnalysisFunctionArn:
    Description: "Youtube Comment Sentiment Analysis Lambda Function ARN"
    Value: !GetAtt YoutubeCommentSentimentAnalysisFunction.Arn
  YoutubeCommentSentimentAnalysisBucketArn:
    Description: "Youtube Comment Sentiment Analysis Bucket ARN"
    Value: !GetAtt S3Bucket.Arn
  YoutubeCommentSentimentAnalysisGlueDatabaseName:
    Description: "Youtube Comment Sentiment Analysis Glue Database Name"
    Value: !Ref GlueDatabase
  YoutubeCommentSentimentAnalysisGlueAnalyticsTableName:
    Description: "Youtube Comment Sentiment Analysis Glue Table Name"
    Value: !Ref GlueTable
  YoutubeCommentSentimentAnalysisDynamoDBTableName:
    Description: "Youtube Comment Sentiment Analysis DynamoDB Table Name"
    Value: !Ref DynamoDBTable