AWSTemplateFormatVersion: '2010-09-09'

Transform: 
  - AWS::Serverless-2016-10-31

Description: Youtube comment sentiment analysis service

Parameters:
  Env:
    Type: String
    Default: test
    AllowedValues:
      - test
      - prod
    Description: Environment to deploy the stack

Resources:
  YoutubeCommentSentimentAnalysisFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${Env}-youtube-comment-sentiment-analysis
      Handler: app.lambda_handler
      CodeUri: ./src
      Description: Fetches comments from youtube video and performs sentiment analysis
      Architectures:
        - x86_64
      Runtime: python3.12
      Timeout: 30
      Tracing: Active
      Environment:
        Variables:
          POWERTOOLS_SERVICE_NAME: ProdYoutubeCommentSentimentAnalysis
          POWERTOOLS_METRICS_NAMESPACE: ProdYoutubeCommentSentimentAnalysis
          LOG_LEVEL: INFO
          BUCKET_NAME: !Ref S3Bucket
          ENVIROMENT: !Ref Env
      Policies: 
        - ComprehendBasicAccessPolicy: {}
        - S3WritePolicy:
            BucketName: !Ref S3Bucket
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn: !Sub arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:test/YoutubeSentimentAnalysis-CVq1ik
      Tags:
        Service: !Ref AWS::StackName
        Env: !Ref Env
        awsApplication: !GetAtt AppRegistry.ApplicationTagValue

  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${Env}-youtube-comment-sentiment-analysis
      Tags:
        - Key: Service
          Value: !Ref AWS::StackName
        - Key: Env
          Value: !Ref Env
        - Key: awsApplication
          Value: !GetAtt AppRegistry.ApplicationTagValue

  GlueDatabase:
    Type: AWS::Glue::Database
    Properties:
      CatalogId: !Ref "AWS::AccountId"
      DatabaseInput:
        Name: !Sub ${Env}_youtube_comment

  GlueTable:
    Type: AWS::Glue::Table
    Properties:
      CatalogId: !Ref "AWS::AccountId"
      DatabaseName: !Ref GlueDatabase
      TableInput:
        Name: !Sub ${Env}_youtube_comment_analytics
        TableType: EXTERNAL_TABLE
        StorageDescriptor:
          Columns:
            - Name: id
              Type: string
            - Name: channelId
              Type: string
            - Name: videoId
              Type: string
            - Name: textDisplay
              Type: string
            - Name: textOriginal
              Type: string
            - Name: authorDisplayName
              Type: string
            - Name: authorProfileImageUrl
              Type: string
            - Name: authorChannelUrl
              Type: string
            - Name: authorChannelId
              Type: string
            - Name: canRate
              Type: boolean
            - Name: viewerRating
              Type: string
            - Name: likeCount
              Type: int
            - Name: publishedAt
              Type: timestamp
            - Name: updatedAt
              Type: timestamp
            - Name: parentId
              Type: string
            - Name: sentiment
              Type: string
            - Name: sentimentScorePositive
              Type: float
            - Name: sentimentScoreNegative
              Type: float
            - Name: sentimentScoreNeutral
              Type: float
          Location: !Sub s3://${S3Bucket}/data/
          InputFormat: "org.apache.hadoop.mapred.TextInputFormat"
          OutputFormat: "org.apache.hadoop.hive.ql.io.HiveIgnoreKeyTextOutputFormat"
          SerdeInfo:
            SerializationLibrary: org.openx.data.jsonserde.JsonSerDe
        Parameters:
          classification: json
          has_encrypted_data: "false"

  AppRegistry:
    Type: AWS::ServiceCatalogAppRegistry::Application
    Properties:
      Name: !Sub ${Env}-youtube-comment-sentiment-analysis
      Description: Logical application grouping for Youtube Comment Sentiment Analysis resources
      Tags:
        service: !Ref AWS::StackName
        env: !Ref Env

  AppRegistryAssociation:
    Type: AWS::ServiceCatalogAppRegistry::ResourceAssociation
    Properties:
      Application: !Ref AppRegistry
      Resource: !Ref AWS::StackId
      ResourceType: CFN_STACK
  

Outputs:
  YoutubeCommentSentimentAnalysisFunctionArn:
    Description: "Youtube Comment Sentiment Analysis Lambda Function ARN"
    Value: !GetAtt YoutubeCommentSentimentAnalysisFunction.Arn
  YoutubeCommentSentimentAnalysisBucketArn:
    Description: "Youtube Comment Sentiment Analysis Bucket ARN"
    Value: !GetAtt S3Bucket.Arn
  YoutubeCommentSentimentAnalysisGlueDatabaseName:
    Description: "Name of the Glue Database"
    Value: !Ref GlueDatabase
  YoutubeCommentSentimentAnalysisGlueAnalyticsTableName:
    Description: "Name of the Glue Table"
    Value: !Ref GlueTable