AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Youtube comment sentiment analysis service

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - prod
    Description: Environment

Resources:
  YoutubeCommentSentimentAnalysisFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: youtube-comment-sentiment-analysis
      Handler: lambda_handler
      CodeUri: src
      Description: Fetches comments from youtube video and performs sentiment analysis
      Architectures:
        - x86_64
      Runtime: python3.12
      Timeout: 30
      Tracing: Active
      Environment:
        Variables:
          POWERTOOLS_SERVICE_NAME: YoutubeCommentSentimentAnalysis
          POWERTOOLS_METRICS_NAMESPACE: YoutubeCommentSentimentAnalysis
          LOG_LEVEL: INFO
      Policies: 
        - S3WritePolicy:
            BucketName: !Ref YoutubeCommentSentimentAnalysisBucket
      Tags:
        service: !Ref AWS::StackName
        environment: !Ref Environment

  YoutubeCommentSentimentAnalysisBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: youtube-comment-sentiment-analysis


Outputs:
  YoutubeCommentSentimentAnalysisFunctionArn:
    Description: "Youtube Comment Sentiment Analysis Lambda Function ARN"
    Value: !GetAtt YoutubeCommentSentimentAnalysisFunction.Arn
  YoutubeCommentSentimentAnalysisBucketArn:
    Description: "Youtube Comment Sentiment Analysis Bucket ARN"
    Value: !GetAtt YoutubeCommentSentimentAnalysisBucket.Arn

