on:
  push:
    branches:
      - test
      - main
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

env:
  ENVIRONMENT: >
    ${{ 
      github.ref_name == 'main' && 'prod' || 
      github.ref_name == 'test' && 'test'
    }}
  SAM_CLI_TELEMETRY: 0

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup SAM
        uses: aws-actions/setup-sam@v2
        with:
          use-installer: true
      - name: Validate SAM Template
        run: sam validate --lint --config-env ${{ env.ENVIRONMENT }}
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - name: Set up Python
        run: uv python install
      - name: Install the project
        run: uv sync --group test
      - name: Run tests
        run: uv run pytest -s .

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v3
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          audience: sts.amazonaws.com
          aws-region: eu-west-1
          role-to-assume: arn:aws:iam::639269844451:role/github-actions
      - name: Setup SAM
        uses: aws-actions/setup-sam@v2
        with:
          use-installer: true
      # Build inside Docker containers
      - name: Build SAM Application
        run: sam build --config-env ${{ env.ENVIRONMENT }}
      # Package SAM Application
      - name: Package SAM Application
        run: sam package --config-env ${{ env.ENVIRONMENT }}
      # Prevent prompts and failure when the stack is unchanged
      - name: Deploy SAM Application
        run: sam deploy --config-env ${{ env.ENVIRONMENT }}
